from itertools import product


def rref_f2(rows):
    rows = [row[:] for row in rows]
    if not rows:
        return rows, []
    m = len(rows)
    n = len(rows[0])
    pivots = []
    r = 0
    for c in range(n):
        pivot = None
        for i in range(r, m):
            if rows[i][c] & 1:
                pivot = i
                break
        if pivot is None:
            continue
        rows[r], rows[pivot] = rows[pivot], rows[r]
        for i in range(m):
            if i != r and (rows[i][c] & 1):
                rows[i] = [(a ^ b) for a, b in zip(rows[i], rows[r])]
        pivots.append(c)
        r += 1
        if r == m:
            break
    return rows, pivots


def rank_f2(rows, ncols=None):
    if not rows:
        return 0
    if ncols is None:
        ncols = len(rows[0])
    _, pivots = rref_f2([row[:ncols] for row in rows])
    return len(pivots)


def span_dim(vectors, ambient_dim):
    if not vectors:
        return 0
    return rank_f2([v[:] for v in vectors], ambient_dim)


def quotient_dim(total_dim, rel_rows):
    return total_dim - rank_f2(rel_rows, total_dim)


def make_standard_basis(dim, offset, local_dim):
    out = []
    for i in range(local_dim):
        v = [0] * dim
        v[offset + i] = 1
        out.append(v)
    return out


def add_vec(u, v):
    return [(a ^ b) for a, b in zip(u, v)]


class Diagram:
    def __init__(self, ambient_dim, local_dims, local_to_global, overlap_generators):
        self.ambient_dim = ambient_dim
        self.local_dims = local_dims
        self.local_to_global = local_to_global
        self.overlap_generators = overlap_generators
        self.offsets = {}
        s = 0
        for v, d in local_dims.items():
            self.offsets[v] = s
            s += d
        self.total_dim = s

    def coproduct_basis(self, v):
        return make_standard_basis(self.total_dim, self.offsets[v], self.local_dims[v])

    def relation_rows(self):
        rows = []
        for u, v, gens in self.overlap_generators:
            for gu, gv in gens:
                row = [0] * self.total_dim
                ou = self.offsets[u]
                ov = self.offsets[v]
                for i, x in enumerate(gu):
                    row[ou + i] ^= (x & 1)
                for i, x in enumerate(gv):
                    row[ov + i] ^= (x & 1)
                rows.append(row)
        return rows

    def colimit_dim(self):
        return quotient_dim(self.total_dim, self.relation_rows())

    def phi_rows(self):
        rows = []
        for a in range(self.ambient_dim):
            row = [0] * self.total_dim
            for v, mats in self.local_to_global.items():
                off = self.offsets[v]
                for i in range(self.local_dims[v]):
                    row[off + i] = mats[i][a]
            rows.append(row)
        return rows

    def x_dim(self):
        vectors = []
        for v, mats in self.local_to_global.items():
            vectors.extend(mats)
        return span_dim(vectors, self.ambient_dim)

    def induced_rank(self):
        rels = self.relation_rows()
        phi = self.phi_rows()
        basis = []
        for j in range(self.total_dim):
            e = [0] * self.total_dim
            e[j] = 1
            basis.append(e)
        q_basis = []
        for e in basis:
            if rank_f2(rels + q_basis + [e], self.total_dim) > rank_f2(rels + q_basis, self.total_dim):
                q_basis.append(e)
        images = []
        for q in q_basis:
            img = [0] * self.ambient_dim
            for v, mats in self.local_to_global.items():
                off = self.offsets[v]
                for i in range(self.local_dims[v]):
                    if q[off + i]:
                        img = add_vec(img, mats[i])
            images.append(img)
        return span_dim(images, self.ambient_dim)

    def kappa(self):
        return self.colimit_dim() - self.induced_rank()


def test_colimit_kernel_identity_on_overlap_generated_example():
    # Two local 1-cycles identified on overlap; no higher-order kernel.
    # C_R dimension = 1, X_R dimension = 1, kappa_R = 0.
    D = Diagram(
        ambient_dim=1,
        local_dims={"u": 1, "v": 1},
        local_to_global={
            "u": [[1]],
            "v": [[1]],
        },
        overlap_generators=[
            ("u", "v", [([1], [1])]),
        ],
    )
    assert D.colimit_dim() == 1
    assert D.x_dim() == 1
    assert D.induced_rank() == 1
    assert D.kappa() == 0
    assert D.x_dim() == D.colimit_dim() - D.kappa()


def test_colimit_kernel_detects_higher_order_relation():
    # Three local classes with no pairwise overlap relations, but all map to the same global class.
    # This forces a nontrivial kernel not generated by pairwise overlap identifications.
    # C_R dimension = 3, X_R dimension = 1, kappa_R = 2.
    D = Diagram(
        ambient_dim=1,
        local_dims={"a": 1, "b": 1, "c": 1},
        local_to_global={
            "a": [[1]],
            "b": [[1]],
            "c": [[1]],
        },
        overlap_generators=[],
    )
    assert D.colimit_dim() == 3
    assert D.x_dim() == 1
    assert D.induced_rank() == 1
    assert D.kappa() == 2
    assert D.x_dim() == D.colimit_dim() - D.kappa()


def test_kernel_is_the_exact_obstruction_to_recoverability_from_pairwise_overlap_quotient():
    D1 = Diagram(
        ambient_dim=1,
        local_dims={"a": 1, "b": 1, "c": 1},
        local_to_global={
            "a": [[1]],
            "b": [[1]],
            "c": [[1]],
        },
        overlap_generators=[],
    )
    D2 = Diagram(
        ambient_dim=3,
        local_dims={"a": 1, "b": 1, "c": 1},
        local_to_global={
            "a": [[1, 0, 0]],
            "b": [[0, 1, 0]],
            "c": [[0, 0, 1]],
        },
        overlap_generators=[],
    )
    assert D1.colimit_dim() == D2.colimit_dim() == 3
    assert D1.kappa() == 2
    assert D2.kappa() == 0
    assert D1.x_dim() == 1
    assert D2.x_dim() == 3
    assert D1.x_dim() == D1.colimit_dim() - D1.kappa()
    assert D2.x_dim() == D2.colimit_dim() - D2.kappa()
